# go-react-admin 配置文件

# 服务器配置
server:
  port: 8080
  mode: debug # debug, release, test

# 数据库配置
mysql:
  host: 127.0.0.1
  port: 2603
  username: root
  password: 123456
  dbname: go_react_admin
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai

# Redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

# 日志配置
log:
  level: info
  format: json
  output: file

# JWT配置
jwt:
  secret: go-react-admin-secret
  expire: 24 # 小时

# 多租户配置
multi_tenant:
  enabled: true
  mode: shared_schema # shared_schema, independent_schema

# 系统配置
system:
  name: go-react-admin
  version: 1.0.0
  theme: light # light, dark