FROM golang:1.23-alpine

# Install development tools
#RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Install air for hot reload
#RUN go install github.com/cosmtrek/air@latest

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Use air for hot reload
#CMD ["air", "-c", ".air.toml"]
CMD ["go", "run", "main.go"]
